package com.sol.food.domain.model.wine
enum class WineType(val displayName: String) {
    WHITE_WINE("White Wine"),
    DRY_WHITE_WINE("Dry White Wine"),
    ASSYRTIKO("Assyrtiko"),
    PINOT_BLANC("Pinot Blanc"),
    CORTESE("Cortese"),
    ROUSSANNE("Roussanne"),
    MOSCHOFILERO("Moschofilero"),
    MUSCADET("Muscadet"),
    VIOGNIER("Viognier"),
    VERDICCHIO("Verdicchio"),
    GRECO("Greco"),
    MARSANNE("Marsanne"),
    WHITE_BURGUNDY("White Burgundy"),
    CHARDONNAY("Chardonnay"),
    GRUENER_VELTLINER("Grüner Veltliner"),
    WHITE_RIOJA("White Rioja"),
    FRASCATI("Frascati"),
    GAVI("Gavi"),
    L_ACADIE_BLANC("L'Acadie Blanc"),
    TREBBIANO("Trebbiano"),
    SAUVIGNON_BLANC("Sauvignon Blanc"),
    CATARRATTO("Catarratto"),
    ALBARINO("Albariño"),
    ARNEIS("Arneis"),
    VERDEJO("Verdejo"),
    VERMENTINO("Vermentino"),
    SOAVE("Soave"),
    PINOT_GRIGIO("Pinot Grigio"),
    DRY_RIESLING("Dry Riesling"),
    TORRONTES("Torrontés"),
    MUELLER_THURGAU("Müller-Thurgau"),
    GRECHETTO("Grechetto"),
    GEWURZTRAMINER("Gewürztraminer"),
    CHENIN_BLANC("Chenin Blanc"),
    WHITE_BORDEAUX("White Bordeaux"),
    SEMILLON("Semillon"),
    RIESLING("Riesling"),
    SAUTERNES("Sauternes"),
    SYLVANER("Sylvaner"),
    LILLET_BLANC("Lillet Blanc"),
    RED_WINE("Red Wine"),
    DRY_RED_WINE("Dry Red Wine"),
    PETITE_SIRAH("Petite Sirah"),
    ZWEIGELT("Zweigelt"),
    BACO_NOIR("Baco Noir"),
    BONARDA("Bonarda"),
    CABERNET_FRANC("Cabernet Franc"),
    BAIRRADA("Bairrada"),
    BARBERA_WINE("Barbera"),
    PRIMITIVO("Primitivo"),
    PINOT_NOIR("Pinot Noir"),
    NEBBIOLO("Nebbiolo"),
    DOLCETTO("Dolcetto"),
    TANNAT("Tannat"),
    NEGROAMARO("Negroamaro"),
    RED_BURGUNDY("Red Burgundy"),
    CORVINA("Corvina"),
    RIOJA("Rioja"),
    COTES_DU_RHONE("Côtes du Rhône"),
    GRENACHE("Grenache"),
    MALBEC("Malbec"),
    ZINFANDEL("Zinfandel"),
    SANGIOVESE("Sangiovese"),
    CARIGNAN("Carignan"),
    CARMENERE("Carmenere"),
    CESANESE("Cesanese"),
    CABERNET_SAUVIGNON("Cabernet Sauvignon"),
    AGLIANICO("Aglianico"),
    TEMPRANILLO("Tempranillo"),
    SHIRAZ("Shiraz"),
    MOURVEDRE("Mourvèdre"),
    MERLOT("Merlot"),
    NERO_D_AVOLA("Nero d'Avola"),
    BORDEAUX("Bordeaux"),
    MARSALA("Marsala"),
    PORT("Port"),
    GAMAY("Gamay"),
    DORNFELDER("Dornfelder"),
    CONCORD_WINE("Concord Wine"),
    SPARKLING_RED_WINE("Sparkling Red Wine"),
    PINOTAGE("Pinotage"),
    AGIORGITIKO("Agiorgitiko"),
    DESSERT_WINE("Dessert Wine"),
    PEDRO_XIMENEZ("Pedro Ximénez"),
    MOSCATO("Moscato"),
    LATE_HARVEST("Late Harvest"),
    ICE_WINE("Ice Wine"),
    WHITE_PORT("White Port"),
    LAMBRUSCO_DOLCE("Lambrusco Dolce"),
    MADEIRA("Madeira"),
    BANYULS("Banyuls"),
    VIN_SANTO("Vin Santo"),
    ROSE_WINE("Rosé Wine"),
    SPARKLING_ROSE("Sparkling Rosé"),
    SPARKLING_WINE("Sparkling Wine"),
    CAVA("Cava"),
    CREMANT("Crémant"),
    CHAMPAGNE("Champagne"),
    PROSECCO("Prosecco"),
    SPUMANTE("Spumante"),
    SHERRY("Sherry"),
    CREAM_SHERRY("Cream Sherry"),
    DRY_SHERRY("Dry Sherry"),
    VERMOUTH("Vermouth"),
    DRY_VERMOUTH("Dry Vermouth"),
    FRUIT_WINE("Fruit Wine"),
    MEAD("Mead");

    companion object {
        val size = values().size
        operator fun get(index: Int): WineType = values()[index]
    }
}